### ISSUE TITLE
AWS_ECR_ACCOUNT_URL usage makes invalid docker image

### ISSUE THREAD

**Issue by alex-hsp** [CircleCI-Public/aws-ecr-orb#104]
### Orb version

6.9.1

### What happened

With the new update, AWS_ECR_ACCOUNT_URL is used by aws cli login command and requires https:// at the beginning of AWS_ECR_ACCOUNT_URL. But AWS_ECR_ACCOUNT_URL is also used to assemble docker image tag like `$<<parameters.account-url>>/<<parameters.repo>>:${tag}`. This https:// at the beginning makes tag invalid.

### Expected behavior

The way AWS_ECR_ACCOUNT_URL is handled should change. Either https:// must be stripped when creating image name, or must be added if not found in aws login command

**Comment by lokst** [comment]
Hi @alex-hsp , are you referring to the `ecr-login` command of the orb? I don't think you need to specify "https" in the value of `AWS_ECR_ACCOUNT_URL `for the login to work.

Looking at the example in the aws docs at https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html, we can see that "https" is not needed:

```
aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
```

**Comment by alex-hsp** [comment]
Indeed. Using project env var with login url without https:// and specifying its name as account-url param for build-and-push image  job worked for me. Thanks!
