### ISSUE TITLE
Adding layers caching 

### ISSUE THREAD

**Issue by idobry** [CircleCI-Public/aws-ecr-orb#111]
## What would you like to be added
run builds with caching layers mechanism

## Why is this needed
builds' time redundancy is always something we should aim for

**Comment by gmemstr** [comment]
@idobry CircleCI offers Docker Layer Caching - is this a seperate feature from this? https://circleci.com/docs/2.0/docker-layer-caching/

**Comment by gmemstr** [comment]
Closing this issue since this is a feature of CircleCI, as mentioned above.

**Comment by max-xsell** [comment]
How we can integrate it with aws-ecr? Because the docker layer cache is inside of the steps.
