### ISSUE TITLE
.dockerignore files are ignored due to Docker version

### ISSUE THREAD

**Issue by JeroenRijks** [CircleCI-Public/aws-ecr-orb#118]
### Orb version

6.13.0

### What happened

The `build-image` command and anything that uses it completely ignores the `.dockerignore` file, creating a Dockerfile with files in it that it might not ought to have.

### Expected behavior

The `.dockerignore` file should dictate which files are ignored when building the Docker image.

### Discussion
The `build-image` command's source code shows that it runs `docker build ...  -f <<parameters.path>>/<<parameters.dockerfile>>`. 

When I run this locally (v19.03.6), the behaviour I observe is that the .dockerignore file is respected, and files that I exclude from my docker image are excluded successfully. However, the executor used in the orb has an older version of Docker, which doesn't use .dockerignore files.

I was able to fix this in my pipeline by using a different executor, as shown:
```
executors:
  ubuntu2004:
    machine:
        image: ubuntu-2004:202010-01
```

However, it would be nice if this was fixed at the source. I'm happy to implement this myself, but I'll need some help with identifying any breaking changes that might occur if the orb starts using this `ubuntu-2004:202010-01` Docker image as its default executor instead.

**Comment by brivu** [comment]
Hi @tkratky,   

It looks like the latest ubuntu images has version 20.10.12 of Docker installed, which supports the `dockerignore` file.  I'm going to make the the default executor for this orb in this next major version change that I am working on now.  This issue will be taken care of in the next couple of weeks.  

Thanks! 
Brian
