### ISSUE TITLE
Docker cache

### ISSUE THREAD

**Issue by max-xsell** [CircleCI-Public/aws-ecr-orb#122]
Hi

Somebody can help me with an example how i can configure the cache in the feature?

My file

`\`
version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@6.15.0
  kubernetes: circleci/kubernetes@0.3.0

workflows:
  version: 2
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-and-push-image
          account-url: AWS_ECR_URL
          region: AWS_DEFAULT_REGION
          use-docker-layer-caching: true
          remote-docker-layer-caching: true
          repo: XXXXX
          path: ./
          tag: ${CIRCLE_SHA1}
          # Uncomment if the repository does not yet exist
          # create-repo: true
          requires:
            - Continuos-integration
          filters:
            branches:
              only:
                - main    
                - develop        

``

But it does not have layer caching

thank you

**Comment by gmemstr** [comment]
@max-xsell Are you on our free plan at all? Docker layer caching is only available on Performance and Scale plans.

**Comment by brivu** [comment]
Closing issue for now.  Please reopen if the issue remains
