### ISSUE TITLE
Support for AWS ECR public registries

### ISSUE THREAD

**Issue by nonsense** [CircleCI-Public/aws-ecr-orb#128]
## What would you like to be added

At the moment when I try to authenticate with a public AWS ECR registry, I get the following error:

```
#!/bin/bash -eo pipefail
# get-login-password returns a password that we pipe to the docker login command
aws ecr get-login-password --region $AWS_REGION --profile default | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
Error response from daemon: login attempt to https://**************/v2/ failed with status: 400 Bad Request
```

I've tried various options for `AWS_ECR_ACCOUNT_URL` env var, such as `public.ecr.aws/xxxxxxxx` or `public.ecr.aws`, but nothing seems to work.

I believe the reason is the use of `aws ecr`, instead of `aws ecr-public`, which is suggested by AWS when inspecting the `View push comments` screen:

```
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/xxxxxxxx
```

---

Additionally I had to add more permissions to the AWS IAM account policy when switching from Private to Public registry, namely:

```
                "ecr-public:*",
                "sts:*"
```

**Comment by allanvobraun** [comment]
Please, any workarounds?

**Comment by brivu** [comment]
Hey @allanvobraun, 

I'm working on a major refactor of this Orb right now and will include public registry support.  It should be done at the end of this week or early next week.  

Thanks for letting us know! 

Best, 
Brian

**Comment by allanvobraun** [comment]
It will be amazing! It will greatly reduce my setup. I'm currently using the aws cli orb. 
If you want help testing let me know.

**Comment by govinaeyum** [comment]
Hello @brivu, I am using the aws-ecr orb to deploy image to public ecr but encountered authentication issue. Any update on this orb to include public repo deployment. Orb works fine with private repo. Thanks.

**Comment by brivu** [comment]
Hey @allanvobraun! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian
