### ISSUE TITLE
Add a step name during ECR repository creation

### ISSUE THREAD

**Issue by jeremietharaud** [CircleCI-Public/aws-ecr-orb#129]
## What would you like to be added
Hi all,

The name of the step that creates the ECR repository (build-and-push-image command) is missing.
Instead, we see something like this in the CircleCI web interface:

```
aws ecr describe-repositories --profile default --region $AWS_DEFAULT_REGION --repository-names ... > /dev/null 2>&1 || \
aws ecr create-repository --profile default --region $AWS_DEFAULT_REGION --repository-name ... --image-scanning-configuration scanOnPush=true
```

## Why is this needed

Improve readability of CircleCI workflows.

**Comment by brivu** [comment]
Hey @jeremietharaud , 

I'm Brian from CircleCI's CPE Team.  I just wanted to let you know thatI've taken care of this issue and it'll be merged with the next PR.

Thanks for your contribution! 
Brian
