### ISSUE TITLE
Use standard environment variable for aws region

### ISSUE THREAD

**Issue by mark-ship-it** [CircleCI-Public/aws-ecr-orb#131]
### Orb version
6.15.2

### What happened
AWS_REGION is a standard environment variable in the AWS SDK.  However, I think for this orb, the convention is to use environment variables that are compatible with the aws cli

### Expected behavior
I believe AWS_DEFAULT_REGION should be the environment variable for region as defined here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html.  The other AWS environment variables used in this orb follow convention.

**Comment by brivu** [comment]
Hey @mark-ship-it , 

I'm Brian from CircleCI's CPE Team.  I just wanted to let you know thatI've taken care of this issue and it'll be merged with the next PR.

Thanks for your contribution! 
Brian
