### ISSUE TITLE
aws-ecr@6.15.3 orb failing to install aws cli

### ISSUE THREAD

**Issue by SinghJ3** [CircleCI-Public/aws-ecr-orb#134]
### Orb version

aws-ecr@6.15.3
### What happened

I am using aws-ecr@6.15.3 orb to push docker image on ecr repo. But it is failing at "Install AWS CLI v2" step while using windows executor.

### Expected behavior

It should install AWS CLI v2

**Comment by Spiroman** [comment]
Try upgrading the machine you run the CI on (upgrading which windows orb you're using).
We had the same issue, switching from ubuntu 16.04 to 20.04 fixed it.

**Comment by brivu** [comment]
Issue resolved with PR https://github.com/CircleCI-Public/aws-ecr-orb/pull/137
