### ISSUE TITLE
Allow skipping AWS CLI installation if already installed

### ISSUE THREAD

**Issue by andreialecu** [CircleCI-Public/aws-ecr-orb#135]
## What would you like to be added

This orb runs an aws-cli installation even if the cli was already previously installed by a previous job step.

A parameter like `install-cli: false` would be useful.

## Why is this needed

It results in unnecessary work which can slow workflows down a bit. It also reconfigures AWS credentials, which may mess up some setups.

Example workflow log:

<img width="691" alt="Screenshot 2021-03-16 at 12 26 18" src="https://user-images.githubusercontent.com/697707/111294279-d0981480-8652-11eb-846e-0be6f170d059.png">

This workflow sets up the AWS cli, then does some work with it, and then pushes an ecr image. Notice how at the bottom the AWS cli is installed and configured again.

**Comment by brivu** [comment]
Hey @andreialecu, 

By default when you calling the `build-and-push-image` job, there's step that uses the `ecr-login` command.  This command has a step that uses the [AWS CLI Orb](https://github.com/CircleCI-Public/aws-cli-orb/blob/5240e11230c9548d6bd7ee61fef7ff87ca4fb3af/src/scripts/install) to install the CLI.  If the image already has the CLI installed, [it skips it](https://github.com/CircleCI-Public/aws-cli-orb/blob/5240e11230c9548d6bd7ee61fef7ff87ca4fb3af/src/scripts/install.sh#L73) .  

In your workflow above, it looks like you're either calling the `build-and-push-image` command or the `aws-cli/setup` command twice.  In both cases, the step is skipped.  

Let me know if you have any questions and feel free reopen this issue. 

Best, 
Brian

**Comment by brivu** [comment]
Hey @andreialecu, 

This one is on our end.  Let me see if I can get the check to run once and then not again.  I see it in my workflow too.  

Thanks again for pointing that out to us. 

Best, 
Brian
