### ISSUE TITLE
Aws cli install fails

### ISSUE THREAD

**Issue by mikedodd** [CircleCI-Public/aws-ecr-orb#136]
The executor is quite old and using this calls aws install to fail

File "/opt/circleci/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2956, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected ',' or end-of-list in rsa>=3.1.2,<=4.5.0; python_version=="2.7" at ; python_version=="2.7"
You are using pip version 8.1.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Can u please update the default executor

**Comment by JesusValera** [comment]
We are having exactly the same problem.

**Comment by mattwedge** [comment]
Same here

**Comment by mohsinzaheer25** [comment]
I had this issue as well but updating the tag to v6.15.3 fixes the issue.

**Comment by bkovacev** [comment]
> I had this issue as well but updating the tag to v6.15.3 fixes the issue.

Can confirm this has fixed it for us as well.

**Comment by mohsinzaheer25** [comment]
@bkovacev you welcome.

**Comment by KyleTryon** [comment]
Hello all, 
This should be resolved by https://github.com/CircleCI-Public/aws-ecr-orb/pull/137
Please update your orb to version 7.0 and let us know if you continue to experience any issues. Thank you.
Special thanks to @JesusValera  for the PR

**Comment by danielsanfr** [comment]
In version 6.15.3 it works without problems.

![image](https://user-images.githubusercontent.com/3621711/116459583-64592500-a83c-11eb-8f8d-236b6aa4cf7f.png)

But when I upgrade to version 7.0.0, the following error happens:

![image](https://user-images.githubusercontent.com/3621711/116459473-3d9aee80-a83c-11eb-8241-6f002dd98e6e.png)

**Comment by danielsanfr** [comment]
Please, anyone can help me?

**Comment by JesusValera** [comment]
> Please, anyone can help me?

Did you tried with a 6.x version just in case?

**Comment by danielsanfr** [comment]
Thanks @JesusValera for your answer.

As I said at the beginning of my comment https://github.com/CircleCI-Public/aws-ecr-orb/issues/136#issuecomment-828711895:

> _In version 6.15.3 it works without problems._

I don't know what I need to do.

**Comment by JesusValera** [comment]
> Thanks @JesusValera for your answer.
> 
> As I said at the beginning of my comment https://github.com/CircleCI-Public/aws-ecr-orb/issues/136#issuecomment-828711895:
> 
> > _In version 6.15.3 it works without problems._
> 
> I don't know what I need to do.

Ups, that's true I didn't notice.
I'm not sure but I think I have also the same problem.

Regarding your problem, do you really need the version 7?
If it's not the case, I would suggest you to keep the version 6.
