### ISSUE TITLE
Build multi-arch images

### ISSUE THREAD

**Issue by Quantisan** [CircleCI-Public/aws-ecr-orb#140]
## What would you like to be added

Enable building images with multiple architectures, i.e. amd64, arm64, etc.

See https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

## Why is this needed

currently this orb builds to amd64 only.

**Comment by amioranza** [comment]
PR to fix it:
https://github.com/CircleCI-Public/aws-ecr-orb/pull/168

**Comment by brivu** [comment]
Hey @Quantisan and @amioranza, 

I'm Brian from CircleCI's CPE Team.  I just wanted to let you know thatI've taken care of this issue and it'll be merged with the next PR.

Thanks for your contribution! 
Brian
