### ISSUE TITLE
Support BuildKit in the ECR orb

### ISSUE THREAD

**Issue by jherico** [CircleCI-Public/aws-ecr-orb#143]
## What would you like to be added

Support buildkit, either by adding a buildkit boolean parameter to the ORB, or by adding a mechanism to forward specific arbitrary environment variables to the ORB so that I can set `DOCKER_BUILDKIT=1` in my job and have it applied to the `docker build` execution.

## Why is this needed

Executing maven builds inside a docker container is time consuming because there's no easy way to use the CircleCI cache functionality to then mount a restored cache into the docker image.  However, the BuildKit system allows you to do the caching in a Dockerfile configuration so that it will work locally, or on CircleCI.  This is already in place for my direct build jobs, but is incompatible with the ECR scanning because it doesn't support Dockerfiles that rely on the new buildkit syntax and has no way to enable it.

**Comment by diclophis** [comment]
Having buildkit support is crucial for my use-case, see also:https://github.com/CircleCI-Public/cimg-base/issues/110

**Comment by diclophis** [comment]
@jherico any luck on sorting this out?

Is there anything I can help with?

**Comment by jherico** [comment]
@diclophis I've simply disabled the ECR scanning component in the images where I need to use the build kit, because we only use ECR for scanning, and Dockerhub for hosting images, so I can work around it.

**Comment by brivu** [comment]
Hey @diclophis and @jherico, 

Thanks for bringing this to our attention.  We're currently considering adding BuildKit support to our `cimg/base` image, which should help you with this issue.  

You can follow this issue [here](https://github.com/CircleCI-Public/cimg-base/issues/147). 

Thanks again, 
Brian
