### ISSUE TITLE
Cannot find a job named build-and-push-image

### ISSUE THREAD

**Issue by bkovacev** [CircleCI-Public/aws-ecr-orb#145]
### Orb version
7.0.0 and 6.15.3

### What happened
Yesterday everything was working fine, today we can't push the builds at all. Nothing has changed. The error messages says as follows:
```
Build-agent version 1.0.65281-d05a3ec8 (2021-05-27T09:09:28+0000)

Configuration errors: 1 error occurred:
	* Cannot find a job named `aws-ecr/build-and-push-image` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'
```
### Expected behavior
It should build the image and push it to ECR.

**Comment by takahash** [comment]
I tried it today and it worked!
What was it?

**Comment by alex-hladun** [comment]
Make sure you are using version 2.1. This is also impossible to diagnose without posting your config.yml

**Comment by bkovacev** [comment]
@alex-hladun I'm unsure how it's impossible to diagnose without my `config.yml` - as it worked flawlessly for over a year then suddenly stopped working over night and then restored itself without any interference. Also, I'm not the only one.

> Make sure you are using version 2.1. This is also impossible to diagnose without posting your config.yml

I am and have been using version 2.1. Also, there was no change in the `config.yml`. 

I'll close this as a one-off.
