### ISSUE TITLE
Proper error messages

### ISSUE THREAD

**Issue by macieyng** [CircleCI-Public/aws-ecr-orb#151]
### Orb version

7.0.0

### What happened

I had this [job](https://app.circleci.com/pipelines/github/netguru/dj-cf-backend/21/workflows/d278697a-82a6-4f6f-aebb-d4655dbe81f4/jobs/78) that had an issue. Error message was telling me that `error authentication with ECR: MissingRegion: could not find region configuration`. After few hours of debugging it turned out that there was no issue with the region, but with the url to my ECR image and it also has nothing to do with region. 
My url looked like `my-ecr-address.region.com:latest` instead of `my-ecr-address.region.com/my-repo:latest`.

Here is my [config](https://app.circleci.com/projects/github/netguru/dj-cf-backend/config/?branchName=master&pipelineNumber=21).

### Expected behavior

I would expect to get the error that would say `Dude, there is something wrong with the url you gave me.` or ideally 
```
You forgot to tell me to what repository you want to push this image to. 
Your args are: 
- url: my-ecr-address.region.com
- repo: missing
- tag: latest
```

Thanks to Al Clark from Circle CI for encouragement to raise this issue here.

**Comment by gmemstr** [comment]
@macieyng This doesn't appear to be related to this orb, but rather with CircleCI itself. I'll check internally to see what this is about.
