### ISSUE TITLE
Do not run docker login if amazon-ecr-credential-helper is installed

### ISSUE THREAD

**Issue by vatima2016** [CircleCI-Public/aws-ecr-orb#152]
### Orb version

7.0.0

### What happened

The ORB fails if a credential helper is installed, for example amazon-ecr-credential-helper.

```
#!/bin/bash -eo pipefail
# get-login-password returns a password that we pipe to the docker login command
aws ecr get-login-password --region $AWS_DEFAULT_REGION --profile default | docker login --username AWS --password-stdin $AWS_ECR_URL

Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior

This line should not be run at all if amazon-ecr-credential-helper is installed:
`aws ecr get-login-password --region $AWS_DEFAULT_REGION --profile default | docker login --username AWS --password-stdin $AWS_ECR_URL`

See https://github.com/awslabs/amazon-ecr-credential-helper for details.

### Why it makes sense
When not using credentials helper the following warning is shown:
```
WARNING! Your password will be stored unencrypted in /home/circleci/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

**Comment by brivu** [comment]
Hello @vatima2016, 

Thanks for bringing this to our attention! I am currently working on a major update for this orb that will address this issue.  I'm hoping to have it ready next week.  

Thanks again!
Brian

**Comment by brivu** [comment]
Hey Cal! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian
