### ISSUE TITLE
7.1.0 and 7.2.0 tags missing

### ISSUE THREAD

**Issue by nairb774** [CircleCI-Public/aws-ecr-orb#155]
### Orb version

7.1.0 and 7.2.0

### What happened

According to https://circleci.com/developer/orbs/orb/circleci/aws-ecr there is a 7.1.0 and a 7.2.0 release, but those tags seem to be missing from the repository. Would it be possible to get them pushed, and/or release notes generated?

![image](https://user-images.githubusercontent.com/128795/130651882-7c13f305-03e8-41c7-840d-21d430330db2.png)

### Expected behavior

Tags and/or release notes should be available for newly released orbs. This makes evaluating the upgrade risk to new orb versions easier.

**Comment by brivu** [comment]
Hey @nairb774 , 

Thanks for letting me know.  I'll see if we can help here internally.  I am closing this issue for now. 

Best, 
Brian
