### ISSUE TITLE
Add dependant parameter detection

### ISSUE THREAD

**Issue by Jaryt** [CircleCI-Public/aws-ecr-orb#157]
## What would you like to be added

Any parameters that require one another to be executed, should inform the user when a dependent parameter is used but the parameter it depends on is not.

Specifically: `remote-docker-layer-caching` depends on `setup-remote-docker`

## Why is this needed

This will create a better user experience as verbose output would inform the user of an error in their config that isn't schema related.

**Comment by brivu** [comment]
Hey Cal! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian
