### ISSUE TITLE
Docker Multi-arch support

### ISSUE THREAD

**Issue by dantetwc** [CircleCI-Public/aws-ecr-orb#162]
## What would you like to be added

Docker Image build with ARM64

## Why is this needed

Since AWS offers ARM server with lower cost and better performance, it is sensible for this orbs to also support ARM Docker image building

**Comment by gmemstr** [comment]
@dantetwc Would you mind elaborating a bit? Have you attempted to build an ARM image and encountered an error? If so, how would you hope this orb better accommodates this use case? Given CircleCI does not offer ARM execution environments at the moment, is cross-arch building something that can be accomplished?

**Comment by amioranza** [comment]
Hey, I did a PR to add support to the multiarch images
https://github.com/CircleCI-Public/aws-ecr-orb/pull/168

**Comment by amioranza** [comment]
> @dantetwc Would you mind elaborating a bit? Have you attempted to build an ARM image and encountered an error? If so, how would you hope this orb better accommodates this use case? Given CircleCI does not offer ARM execution environments at the moment, is cross-arch building something that can be accomplished?

The docker command `buildx` does cross-arch image generation.

May you take a look on the PR I opened yesterday?

**Comment by amioranza** [comment]
Another issue with same request
https://github.com/CircleCI-Public/aws-ecr-orb/issues/140

**Comment by brivu** [comment]
Hey @amioranza , 

I'm Brian from CircleCI's CPE Team.  I just wanted to let you know that I've taken care of this.  I've added support for ARM and it'll be merged with the next PR.

Thanks for your contribution! 
Brian

**Comment by amioranza** [comment]
To anyone who is waiting the official support I just published an alternate version to build multiple platform images based on the CCI original one.

Here is the ORB: https://circleci.com/developer/orbs/orb/sweetgreen/aws-ecr

Thanks @brivu

**Comment by brivu** [comment]
Hey Cal! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian
