### ISSUE TITLE
AWS ECR should be logged in successfully without the error "Error: Cannot perform an interactive login from a non TTY device"

### ISSUE THREAD

**Issue by Bash-mocart** [CircleCI-Public/aws-ecr-orb#164]
## What would you like to be added

aws ecr get-login-password --region $AWS_DEFAULT_REGION --profile default | docker login --username AWS --password-stdin $AWS_ECR_URL 
this fails with the latest version of awscli
docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ECR_URL
this works just fine

## Why is this needed
Log into Amazon ECR step fails with the message "Error: Cannot perform an interactive login from a non TTY device" 
i tried with this docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ECR_URL command and it seem to work just fine 
solves this issue [#163](https://github.com/CircleCI-Public/aws-ecr-orb/issues/163)

**Comment by maximgtoy** [comment]
I played around and found out it was the --profile flag that fails the command, while running `aws ecr get-login-password --region $AWS_DEFAULT_REGION ` in a ssh session in the same container worked completely fine.

**Comment by brivu** [comment]
Hey Cal! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian

**Comment by abbos1117** [comment]
Error: Cannot perform an interactive login from a non TTY device
in gitlab-ci.yaml   :  docker login -u $user -p $pass

**Comment by Malikabdullah33550** [comment]
> Error: Cannot perform an interactive login from a non TTY device in gitlab-ci.yaml : docker login -u $user -p $pass

Did you find a workaround for this? i am also facing the same issue
