### ISSUE TITLE
Add Lifecycle Policies

### ISSUE THREAD

**Issue by thehar** [CircleCI-Public/aws-ecr-orb#173]
## What would you like to be added

The ability to add lifecycle policies in `create-repo` or a separate action manipulating the rules.

https://docs.aws.amazon.com/AmazonECR/latest/userguide/lp_creation.html

## Why is this needed

In order to minimize the amount of ECR repo garbage, lifecycle rules are needed.

**Comment by brivu** [comment]
Hey @thehar, 

I'm Brian from CircleCI's Customer Engineering Team.  I'm working on a major refactor for this orb at the moment and would like some clarification on your request.  According to the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/put-lifecycle-policy.html), the lifecycle policy is stored in a `json` file.  

```
aws ecr put-lifecycle-policy \
    --repository-name "project-a/amazon-ecs-sample" \
    --lifecycle-policy-text "file://policy.json"
```
My question are you planning to have the policy directly in your repo?  If not, where are you having it stored? 

Let me know and I'll do my best to get this added into this next update! 

Best, 
Brian

**Comment by thehar** [comment]
> documentation

Apologies for the latency here. In repo is acceptable to me, yes.

Thanks Brian!
