### ISSUE TITLE
Defining resource-class not working

### ISSUE THREAD

**Issue by TheVaan** [CircleCI-Public/aws-ecr-orb#174]
### Orb version
7.3.0

### What happened
When using the `resource-class` parameter from #159 as described here:
https://github.com/CircleCI-Public/aws-ecr-orb/blob/a44ce37f36b849d4ba853d2b3eee948376b6e1a9/README.md?plain=1#L104
my build process fails with
```
# Error calling job: 'aws-ecr/build-and-push-image'
# Unexpected argument(s): resource-class
```

### Expected behavior
The job should use the given resource_class.

The reason why this wont work is obvious: this parameter isn't defined for the job. It's only defined for the default executor. 
Maybe the documentation is incorrect here?

@craigmcnamara can you explain how to use the parameter?

**Comment by brivu** [comment]
Hey @TheVaan, 

Great catch. The example is missing an `executor` in the job itself.  You can only use  the `resource_class ` parameter if there's a defined executor.  Here's a [link to our documentation](https://circleci.com/docs/2.0/configuration-reference/).

I'll be sure to update the README file.

Thanks again for pointing that out!

Best, 
Brian
