### ISSUE TITLE
Can we have "build-and-push" command added back again?

### ISSUE THREAD

**Issue by SattarLimejump** [CircleCI-Public/aws-ecr-orb#178]
## What would you like to be added

According to the latest version(8.0.0), the "build-and-push" command is gone because it performs the same function as the "build-and-push" job.
Is it possible to have it again?

## Why is this needed

It is very useful when we have multiple workflows in our CI pipeline because it enables us to create custom jobs and simplify configurations by using the custom job in multiple workflows.

**Comment by brivu** [comment]
Hey @SattarLimejump, 

The `build-and-push-image` job basically calls the `ecr-login` command so that you're authenticated before you use the `build-image` command. 

Will using `build-and-push-image` job again or using just the `build-image` command work for your use case?  I am trying to understand your use case better.  If you can show a sample config, that'd really help. 

Best, 
Brian

**Comment by SattarLimejump** [comment]
Hey @brivu,

Thanks for your response,

Let me explain my case first,

this is part of my configs with version number 7.3.0
`  build-push-image:
    executor: node
    parameters:
      tag:
        type: string
    steps:
      - aws-cli/setup
      - aws-cli/role-arn-setup:
          role-arn: "${DEPLOY_ROLE_ARN}"
          profile-name: deployer
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          remote-docker-layer-caching: true
          attach-workspace: true
          skip-when-tags-exist: true
          region: AWS_DEFAULT_REGION
          repo: $CIRCLE_PROJECT_REPONAME
          tag: "<< parameters.tag >>"
          profile-name: deployer

workflows:
  version: 2
  build-and-deploy-image-to-staging:
    jobs:
      - test:
          filters: *master-branch-only
      - build-push-image:
          context: aws-staging-circleci-user
          name: build-and-push-to-staging-ecr
          tag: "staging-<< pipeline.number >>"
          requires:
            - test
          filters: *master-branch-only

  build-and-deploy-image-to-prod:
    jobs:
      - test:
          filters: *tags-only
      - build-push-image:
          context: aws-production-circleci-user
          name: build-and-push-to-prod-ecr
          tag: "${CIRCLE_TAG}"
          requires:
            - test
          filters: *tags-only`
          
As you can see in my config, I've created a new job and running the steps/commands including the build-and-push-image and then I'm using my custom job in two of my workflows,
So, I can set the parameters once and use them multiple times in my workflows,

But with the new version, we don't have "aws-ecr/build-and-push-image" command, so I need to all the job directly in each workflow and repeat the parameters for each,
I can still use aliases to handle this, but I think having the command is a better and cleaner way to handle this,

**Comment by tfielding-sourcepoint** [comment]
What if we'd like to perform some other commands before the build-and-push?  Having the 'command' exposed allows, in my case, to do things like restore circleCI build caches.  This is a critical one for us, please bring back the "build-and-push" command! :)

**Comment by andrew-barnett** [comment]
IMO the command is more flexible than the job, so if you weren't going to keep both you should have removed the job and not the command. (I personally would have kept both.) Not happy to have to go re-architect 50+ repos just because someone arbitrarily decided my use case wasn't valid.

**Comment by brivu** [comment]
Hey Everyone, 

I hear you loud and clear. Let me go back to the team and make a case for this to be added back in. I'm doing a minor update to this orb as we speak and I'll be advocating for the command to be added back in. 

Best, 
Brian

**Comment by brivu** [comment]
Hey everyone, 

I spoke with the team this morning and was able to make a case for the `build-and-push` command to be added back in.

It should be done within a week or so with PR #187 

Best, 
Brian

**Comment by brivu** [comment]
Hello, 

I've added the command back into the orb. The `@dev:alpha` version is live for testing so if you all can give a run and leave me some feedback, that'd be great.  It'll help with merging these changes sooner.

Best, 
Brian
