### ISSUE TITLE
build-image command with push-image: false doesn't output image 

### ISSUE THREAD

**Issue by kovacevicm** [CircleCI-Public/aws-ecr-orb#179]
### Orb version
8.0.0

### What happened
Using `build-image` command  with `push-image: false` causes the build result to only be present in build cache, showing the following warning:
```
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```
The built  image cannot later on be referenced by the tags used for the build.

### Expected behavior
The result of the `build-image` command is an image which can be later on referenced by tags used for the build.

Note: Based on the warning, I assume the issue could be resolved by adding buildx --load option.
https://docs.docker.com/engine/reference/commandline/buildx_build/#load

**Comment by brivu** [comment]
Hey @kovacevicm, 

Thanks for opening this issue.  Let me huddle up with my team and see how we can add this feature. 

Best, 
Brian

**Comment by keen99** [comment]
@brivu you'd need to `--load` instead of `--push` to copy the image from the build context back.

**Comment by keen99** [comment]
but even that's imperfect in some cases.

**Comment by keen99** [comment]
@kovacevicm you should be able to work around this by passing `--load` as an `extra-build-args`  (assuming they're working, which other issues suggest they may not be working completely..)

**Comment by brivu** [comment]
Hey @keen99, 

I went ahead and added this into the `docker-buildx.sh` script. If the `push-image` parameter is set to false, we'll add the `--load` flag so it assumes that the user wants an output when deciding not to push.  
```
  if [ "${PARAM_PUSH_IMAGE}" == "1" ]; then
    set -- "$@" --push
  else
    set -- "$@" --load
  fi
```

This is taken care of in PR #187.  

Hope that helps and thanks for letting us know! 

Best, 
Brian
