### ISSUE TITLE
Problem with profile name when using role-arn to build and push the image

### ISSUE THREAD

**Issue by SattarLimejump** [CircleCI-Public/aws-ecr-orb#180]
### Orb version
8.0.0

### What happened

This version has a problem with role-arn assumption,
When we don't pass "new-profile-name" but we want to assume a role-arn, it sets empty string "" as profile-name for the role assumption step so it gets failed,

If we pass the "new-profile-name" the role assumption part is working but the rest of the steps still using the "default" value for the profile-name, so they don't use the assumed credentials to do the job,

The temporary solution is to just set "default" as value for "new-profile-value", or set same name for all three parameters "new-profile-name", "profile-name" and "source-profile"

### Expected behaviour

Instead of having a parameter named "new-profile-name" I'd suggest having only two parameters "profile-name" and "source-profile" and "source-profile for before assuming the role and" after assuming the role-arn using the profile-name for the next steps.
 
Or if you want to keep the new-profile-name parameter, use new-profile-name for the steps after the role assumption instead of the profile-name would help

**Comment by brivu** [comment]
Hey @SattarLimejump,  

With the new `role-arn-setup` command in the AWS CLI Orb, you need to run the `aws-cli/setup` command first to create the `default` profile with credentials.  

Then, the `aws-cli/role-arn-setup` command creates a new named profile tied to a `role-arn`  and uses the `default` profile you created first in the `aws-cli/setup` command as the source profile to retrieve the static credentials. 

This was the solution for this [issue](https://github.com/CircleCI-Public/aws-cli-orb/issues/57). 

Do you have a profile already setup with credentials before you run the `aws-cli/role-arn-setup` command? If you can provide me with your sample config, that'd help me understand your use case better.  

Best,
Brian

**Comment by SattarLimejump** [comment]
Hey @brivu 

Here is a part of my config which is working because I've passed "new-profile-name: default" to the job:
```
aliases:
   ...
  - &build-default-parameters
      executor: node
      setup-remote-docker: true
      attach-workspace: true
      skip-when-tags-exist: true
      region: '${AWS_DEFAULT_REGION}'
      repo: $CIRCLE_PROJECT_REPONAME
      role-arn: '${DEPLOY_ROLE_ARN}'
      new-profile-name: default
...

workflows:
  version: 2
  build-and-deploy-image-to-staging:
    jobs:
      - test:
          filters: *master-branch-only
      - aws-ecr/build-and-push-image:
          <<: *build-default-parameters
          context: aws-staging-circleci-user
          name: build-and-push-to-staging-ecr
          tag: "staging-<< pipeline.number >>"
          requires:
            - test
          filters: *master-branch-only
```

But if I don't pass it, this will be the output:
```
    - run:
        command: |
          PARAM_AWS_CLI_ACCESS_KEY_ID=$(eval echo "\$$PARAM_AWS_CLI_ACCESS_KEY_ID")
          PARAM_AWS_CLI_SECRET_ACCESS_KEY=$(eval echo "\$$PARAM_AWS_CLI_SECRET_ACCESS_KEY")
          PARAM_AWS_CLI_REGION=$(eval echo "\$$PARAM_AWS_CLI_REGION")
          PARAM_AWS_CLI_ROLE_ARN=$(eval echo "${PARAM_AWS_CLI_ROLE_ARN}")

          aws configure set aws_access_key_id \
              "$PARAM_AWS_CLI_ACCESS_KEY_ID" \
              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
          aws configure set aws_secret_access_key \
              "$PARAM_AWS_CLI_SECRET_ACCESS_KEY" \
              --profile "$PARAM_AWS_CLI_PROFILE_NAME"

          if [ "$PARAM_AWS_CLI_CONFIG_DEFAULT_REGION" = "1" ]; then
              aws configure set default.region "$PARAM_AWS_CLI_REGION" \
                  --profile "$PARAM_AWS_CLI_PROFILE_NAME"
          fi

          if [ "$PARAM_AWS_CLI_CONFIG_PROFILE_REGION" = "1" ]; then
              aws configure set region "$PARAM_AWS_CLI_REGION" \
                  --profile "$PARAM_AWS_CLI_PROFILE_NAME"
          fi

          if [ -n "$PARAM_AWS_CLI_ROLE_ARN" ]; then
              echo "The role-arn parameter is deprecated. Please use the role-arn-setup command."
              aws configure set role_arn "$PARAM_AWS_CLI_ROLE_ARN" \
                  --profile "$PARAM_AWS_CLI_PROFILE_NAME"
          fi
        environment:
          PARAM_AWS_CLI_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
          PARAM_AWS_CLI_CONFIG_DEFAULT_REGION: true
          PARAM_AWS_CLI_CONFIG_PROFILE_REGION: true
          PARAM_AWS_CLI_PROFILE_NAME: default
          PARAM_AWS_CLI_REGION: AWS_DEFAULT_REGION
          PARAM_AWS_CLI_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
        name: Configure AWS Access Key ID
    - run:
        command: "\nPARAM_AWS_CLI_PROFILE_NAME=$(eval echo \"${PARAM_AWS_CLI_PROFILE_NAME}\")\nPARAM_AWS_CLI_SOURCE_PROFILE=$(eval echo \"${PARAM_AWS_CLI_SOURCE_PROFILE}\")\nPARAM_AWS_CLI_ROLE_ARN=$(eval echo \"${PARAM_AWS_CLI_ROLE_ARN}\")\n\nif [ ! -f \"${HOME}/.aws/credentials\" ]; then\n    echo \"Credentials not found. Run setup command before role-arn-setup.\"\n    exit 1\nfi\n    \naws configure set profile.\"${PARAM_AWS_CLI_PROFILE_NAME}\".role_arn \"${PARAM_AWS_CLI_ROLE_ARN}\"\naws configure set profile.\"${PARAM_AWS_CLI_PROFILE_NAME}\".source_profile \"${PARAM_AWS_CLI_SOURCE_PROFILE}\"\n\n\n"
        environment:
          PARAM_AWS_CLI_PROFILE_NAME: ''
          PARAM_AWS_CLI_ROLE_ARN: ${DEPLOY_ROLE_ARN}
          PARAM_AWS_CLI_SOURCE_PROFILE: default
        name: 'Configure role arn for profie '
    - run:
        command: |
          #!/bin/bash
          REGION=$(eval echo "${PARAM_REGION}")
          ACCOUNT_URL="${!PARAM_REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com"
          ECR_COMMAND="ecr"

          if [ "$PARAM_PUBLIC_REGISTRY" == "1" ]; then
              REGION="us-east-1"
              ACCOUNT_URL="public.ecr.aws"
              ECR_COMMAND="ecr-public"
          fi

          if [ -n "${PARAM_PROFILE_NAME}" ]; then
              set -- "$@" --profile "${PARAM_PROFILE_NAME}"
          fi

          if [ -f ~/.docker/config.json ]; then
              echo "Credential helper is already installed"
          else
              aws "${ECR_COMMAND}" get-login-password --region "${REGION}" "$@" | docker login --username AWS --password-stdin "${ACCOUNT_URL}"
          fi
        environment:
          PARAM_PROFILE_NAME: default
          PARAM_PUBLIC_REGISTRY: false
          PARAM_REGION: ${AWS_DEFAULT_REGION}
          PARAM_REGISTRY_ID: AWS_ECR_REGISTRY_ID
        name: Log into Amazon ECR

```

as you see, it does assign the empty string ('') value as profile-name in the role-assume step instead of 'default', and in the next steps it keeps using 'default' as profile-name value,
And if we pass any name other than 'default' to the new-profile-name, it'll create the new profile in the assume-role step, but keeps using the 'default' for the next steps, which will fail.

like this:
```
step 1 - aws-cli/aws-login     --- profile-name: default
step 2 - aws-cli/assume-role --- profile-name (source-profile): default 
                                                    new-profile-name: deployer-profile
step 3 - aws-ecr/login            --- profile-name: default
```
but in step 3 the profile-name should be 'deployer-profile' which has been created by the previous step and is based on the role assumption, not the default one

Hopefully, it's a bit more clear now :)

**Comment by brivu** [comment]
Hey @SattarLimejump, 

If you take a look at PR #184, this issue should be addressed. When a `role-arn`, `source-profile` and `new-profile` parameters are provided, we configure the `role-arn` with the `aws-cli/role-arn-setup` command and then log into ECR with the new profile provided.  

Can you let me know if this is the functionality you're looking for?

If so, I'm doing a minor update to this Orb and this will be included. 

Thanks for filing the issue!

Best, 
Brian
