### ISSUE TITLE
Last version tag has a typo

### ISSUE THREAD

**Issue by jverce** [CircleCI-Public/aws-ecr-orb#190]
### Orb version

8.1.0

### What happened

The last tag/release, which was intended to be `v8.1.0`, is actually `v.8.1.0`, which wasn't detected as a production
release, so the new version is not available in the [orb's page](https://circleci.com/developer/orbs/orb/circleci/aws-ecr)

The `orb-tools/publish` [job execution](https://app.circleci.com/pipelines/github/CircleCI-Public/aws-ecr-orb/1020/workflows/5a2c9c0f-f5f8-4fb4-96be-7b21247cc28c/jobs/4205) contains the following message:
```
Preparing to publish your orb.
Development release detected!

Orb `circleci/aws-ecr@dev:984cb69bcfb2f3e1ad17578f906c8617619cdff2` was published.
Note that your dev label `dev:984cb69bcfb2f3e1ad17578f906c8617619cdff2` can be overwritten by anyone in your organization.
Your dev orb will expire in 90 days unless a new version is published on the label `dev:984cb69bcfb2f3e1ad17578f906c8617619cdff2`.
Please note that this is an open orb and is world-readable.

Orb `circleci/aws-ecr@dev:alpha` was published.
Note that your dev label `dev:alpha` can be overwritten by anyone in your organization.
Your dev orb will expire in 90 days unless a new version is published on the label `dev:alpha`.
Please note that this is an open orb and is world-readable.
```

### Expected behavior

The new version `v8.1.0` should've been automatically published.
A message like this one should appear after executing the `orb-tools/publish` job:
```
Preparing to publish your orb.
Production release detected!
Production version: 8.1.0

Orb `circleci/aws-ecr@8.1.0` was published.
Please note that this is an open orb and is world-readable.
```

This message is present in the corresponding [job](https://app.circleci.com/pipelines/github/CircleCI-Public/aws-ecr-orb/966/workflows/4278c7cd-b64c-473d-ab1f-28f5e9cef7ef/jobs/3542) of the previous version (`v8.0.0`).

**Comment by jverce** [comment]
cc @brivu

**Comment by brivu** [comment]
Great catch @jverce. That's what I get for making a release late at night ;)
