### ISSUE TITLE
Image tag command target-tag parameter eval

### ISSUE THREAD

**Issue by wmiller112** [CircleCI-Public/aws-ecr-orb#197]
## What would you like to be added

Similar to [this issue](https://github.com/CircleCI-Public/aws-ecr-orb/issues/181) about the tag-image source-tag, it would be nice to be able to pass a variable for the target-tag parameter.

## Why is this needed

Ability to use the command for immutable tags.

**Comment by brivu** [comment]
Hi @wmiller112, 

I this has been fixed in the latest PR. I'm about to cut a new patch release right now so it should be available in `v8.1.2`.

Thanks!
Brian
