### ISSUE TITLE
Readd push-image command

### ISSUE THREAD

**Issue by mksplg** [CircleCI-Public/aws-ecr-orb#199]
## What would you like to be added

Up until version 7.3, the command `push-image` was supported. The command pushes an already built image to ECR.

## Why is this needed

We build the image using a gradle docker plugin. The reason to not use native `docker build` directly is, that the gradle plugin can use the build artefact from previous gradle build steps.

We only want to push the already existing image to ECR

**Comment by ryankbern** [comment]
This would be useful for us as well as we build our docker images using nix. Right now we use `ecr-login` and then run a script to tag and push the images.

**Comment by mishabruml** [comment]
yes please. we need to run a snyk scan on the built image before pushing it

**Comment by liuliu** [comment]
Anything prevents to continue use 7.3 until this added? Any gotchas?

**Comment by brivu** [comment]
Hey Everyone, 

Just wanted to let you know that I am working on the bug fixes for this orb and will add the push command back. 

Thanks for everyone's contributions. 

Best, 
Brian
