### ISSUE TITLE
RoleArn validation error in v8.1

### ISSUE THREAD

**Issue by ffinkbe** [CircleCI-Public/aws-ecr-orb#203]
### Orb version

version >= 8.1.0

### What happened

When running ecr-login on `8.0.0` this works:
```
- aws-ecr/ecr-login:
    source-profile: circleci
    new-profile-name: ecr
    profile-name: ecr
    role-arn: '${AWS_ECR_ROLE_ARN}'
```

However due to the extra-build-args bug fixed in `8.1.1` I had to update the version. 
Now the same code does not work anymore. 

Error output:
```
Parameter validation failed:
Invalid length for parameter RoleArn, value: 19, valid min length: 20
Error: Cannot perform an interactive login from a non TTY device
```

I assume this is a bug since my config has not changed in the ecr-login block. The given `role-arn` is the same and also longer than 20 characters. 
The issue only apperas on versions >= 8.1.0.

The error seems to be raised in this line: https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/scripts/ecr-login.sh#L20

### Expected behavior
A successful login as it happened in version 8.0.0

## Edit:
Debugging this a little further I am getting `role_arn = ${AWS_ECR_ROLE_ARN}` in the `.aws/config` with the new versions. Considering that this code has not substantially changed I assume the issue is with the aws-cli dependency change from `aws-cli@2.1.0` in `v8.0.0` to `aws-cli@3.1`

https://github.com/CircleCI-Public/aws-ecr-orb/blob/v8.1.2/src/@orb.yml#L11
The error therefore might be with the aws-cli project

**Comment by zbroniszewski** [comment]
@ffinkbe I've mentioned this issue as well here:
https://github.com/CircleCI-Public/aws-ecr-orb/issues/194

It appears we are waiting for a new release, [one user points out](https://github.com/CircleCI-Public/aws-ecr-orb/pull/196#issuecomment-1132933563) that the latest `aws-ecr` orb did not pick up the latest patch from the `aws-cli` orb which is where this issue was ultimately resolved. (So it seems)

**Comment by vatima2016** [comment]
Please update to **aws-cli@3.1.1**: there is a fix https://github.com/CircleCI-Public/aws-cli-orb/issues/105

**Comment by brivu** [comment]
Closing this issue since the current version of this orb imports `aws-cli@3.1.4`

**Comment by Pitta** [comment]
I am getting this error today.
On version `circleci/aws-ecr@8.2.1`

Should I open a new ticket?
