### ISSUE TITLE
"build-image" running twice per job, is it possible?

### ISSUE THREAD

**Issue by zbroniszewski** [CircleCI-Public/aws-ecr-orb#204]
### Orb version
8.1.2

### What happened
While digging through the `aws-ecr-orb` code, I spotted something that I can only reason to be an issue. If an issue, it is certainly a relatively larger issue that deserves attention.

It appears that under a condition in which the `role-arn` and `new-profile-name` parameters are set on the `build-and-push-image` job, that the `build-image` command will be called twice.

The source:
https://github.com/CircleCI-Public/aws-ecr-orb/blame/master/src/commands/build-and-push-image.yml#L265-L306

^ The only difference between these two steps is that one adds the `lifecycle-policy-path` parameter to the `build-image` command. Other than that, they share the same exact conditional. Although they do differ in the usage of the `when` and `unless` clauses, which are effectively the same to my knowledge.

I dug deeper into the `build-image` command to see if I could disprove that it could be run twice with this addition of the `lifecycle-policy-path` parameter. However, in the case that it is either set or not set, it appears it will have no effect, and `build-image` should indeed run twice. `build-image` uses the `docker-buildx.sh` script, and there are limited references to this `lifecycle-policy-path` parameter. (It's clear that it will have no effect in stopping the entire script from executing):
https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/scripts/docker-buildx.sh#L39-L43

Side note:
Could this be the culprit of why Docker Layer Caching with this orb does not work in CircleCI? I am personally confident we've set things up ideally, though this orb has given us issues. The CircleCI team wasn't able to do much, other than show that we had one line of difference in our Docker build output from one build in one pipeline to the next. (Which likely is telling, but requires more digging into)

### Expected behavior
The two steps mentioned, which both call the `build-image` command, should not depend on the same conditional. I *suspect* one was intended to be called if `role-arn` and `new-profile-name` were set, but not `lifecycle-policy-path`. And the other was intended to be called if `role-arn`, `new-profile-name` and `lifecycle-policy-path` were all set.

**Comment by brivu** [comment]
Hey @zbroniszewski, 

Really good catch and I appreciate it. Let me a take a look and get this fixed with our next release.

Thanks for letting us know! 

-Brian

**Comment by zbroniszewski** [comment]
@brivu You can ignore this. This was my ignorance of the difference between the `when` and `unless` clauses in CircleCI configurations. There's no issue here. (That I can tell)
