### ISSUE TITLE
Please update and release orb with latest downstream updates

### ISSUE THREAD

**Issue by mattops** [CircleCI-Public/aws-ecr-orb#226]
### Orb version

8.1.2

### What happened

This orb pulls in a dependent orb `circleci/aws-cli@3.1`  - there are some bug fixes in this orb which are not compiled into your ECR orb because there hasn't been a recent release.

This issue in particular https://github.com/CircleCI-Public/aws-cli-orb/issues/105

### Solution

Please trigger a new build/release to pull in the latest fixes in the downstream circleci/aws-cli orb.

**Comment by brivu** [comment]
Hey @mattops, 

We've resolved this issue and released version `8.1.3`. 

Best, 
Brian
