### ISSUE TITLE
update remote docker version to no longer be pinned to an old version

### ISSUE THREAD

**Issue by sebastian-lerner** [CircleCI-Public/aws-ecr-orb#229]
### Orb version

?

### What happened

update remote docker version to no longer be an old one and instead rely on the default which will now get updated regularly. https://discuss.circleci.com/t/default-docker-version-for-remote-docker-jobs-changing-on-september-6/45157/2

This line: https://github.com/CircleCI-Public/aws-ecr-orb/blob/20543408da67b0013c3adea8a0dac192ab0b5540/src/commands/build-and-push-image.yml#L233

### Expected behavior

eliminate the pinning of an old remote docker version. instead it uses the default which is being kept current.

**Comment by brivu** [comment]
This issue has been addressed in PR #230
