### ISSUE TITLE
AWS custom key names

### ISSUE THREAD

**Issue by Vlaaaaaaad** [CircleCI-Public/aws-ecr-orb#23]
### Orb version

3.0.0

### What happened

Currently most of the parts of this repo( the build and push image command was of interest to me) use the default AWS keys env vars( `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`).

For some repos we have multiple AWS keys( say one for pushing the image and one for some CI/CD tools) and we push to multiple AWS ECR repos. 

### Expected behavior

It would be awesome if all the components would support given keys. 

Right now we implemented a custom copy/paste jobs that looks like:

```
      - Build and push image:
          repo_name: myRepo
          aws_account: "22222222222222"
          aws_access_key: FANCY_AWS_ACCESS_KEY_ID_1
          aws_secret_key: FANCY_AWS_SECRET_ACCESS_KEY_2
```

**Comment by TomonoriMatsumura** [comment]
I have experienced same kind of problem, too.  

I reported this issue to one of CircleCI support team member and I got message from him that he would create ticket on their BTS, so dev team  might investigate on this issue.  

Hope I could get reply from him, but I am not sure if dev team would really work on this issue.

**Comment by iynere** [comment]
so, what is the specific ask here ? you _should_ already be able to simply pass in different environment variable names to these parameters

**Comment by TomonoriMatsumura** [comment]
https://github.com/CircleCI-Public/aws-ecr-orb/commit/d1d016a859cdf53ed24880b0e90708cb2e45558d

I asked CircleCI support team that the fix added to this commit is not what I want, I want to pass ‘env_var_name’ type rather than ‘string’ type.

I wrote the same kind of process in my orb, and experienced very same behavior what this issue suggests.

I asked if this behavior is what CircleCI team expected or not, and support member said he is not sure and he would ask about this behavior to dev team.

**Comment by TomonoriMatsumura** [comment]
I am sorry, I didn't realize that this is fixed.  

The status of this issue is still open so that the behavior mentioned on this issue is same as I have experienced on my orb project.  

I got message from CircleCI support team, and the solution they suggested is exactly what is done on this orb.

**Comment by illia-sh** [comment]
The issue it still exist even 6.2.0 version. 
If "AWS_ACCESS_KEY_ID" is defined in the environment variables but another variable name defined in the job "FANCY_AWS_ACCESS_KEY_ID_1"
```
      - Build and push image:
          repo_name: myRepo
          aws_account: "22222222222222"
          aws_access_key: FANCY_AWS_ACCESS_KEY_ID_1
```
   It will use "AWS_ACCESS_KEY_ID" from the variables rather then "FANCY_AWS_ACCESS_KEY_ID_1" , same for secret key.  

I made it work only removing the default one "AWS_ACCESS_KEY_ID" from env variables and always using customs name for aws variables.

**Comment by eddiewebb** [comment]
Closing this as seems API has changed since reporting, and `aws-access-key-id` and `aws-secret-access-key` will be properly used if overriden from default env var names.
