### ISSUE TITLE
Can not use environment variable in the path parameter of build-image command

### ISSUE THREAD

**Issue by pepesenaris** [CircleCI-Public/aws-ecr-orb#231]
### Orb version

Affects 8.1.3

### What happened

When the path parameter contains an environment variable its value is not expanded. Instead we get a literal string with the variable name.
For example if we have a step with the following code:
```
echo "export DOCKER_BUILD_PATH='my-custom-directory'" >> $BASH_ENV
```
and we call the command with

```yaml
- aws-ecr-build-image:
    path: $DOCKER_BUILD_PATH
```

The actual value for the path used is `$DOCKER_BUILD_PATH` instead of `my-custom-directory`

### Expected behavior

When the path contains an environment variable, its value should be used instead of the variable name

**Comment by brivu** [comment]
Hey @pepesenaris, 

I just wanted to let you know that we’ve addressed this issue and it’s been merged into #235.

As soon as PR #235 is approved from my team, I’ll merge your changes cut a new release. 

Thank you for your contributions!
-Brian
