### ISSUE TITLE
Can not run build-image command more than once in the same job

### ISSUE THREAD

**Issue by pepesenaris** [CircleCI-Public/aws-ecr-orb#233]
### Orb version

Affects orb 8.1.3

### What happened
If we run the `build-image` command twice in the same job we get a failure.
This is due to running `docker context create builder` a second time and getting a non-zero exit code, given that the builder was already created in the previous command execution.

### Expected behavior

We should be able to run the `build-image` command more than once in the same job.
This is useful when building and pushing multi-staged images, specially if the Dockerfile is optimized to reuse files or layers from previous stages

**Comment by brivu** [comment]
Hey @pepesenaris, 

I just wanted to let you know that we’ve addressed this issue and it’s been merged into #235.

As soon as PR #235 is approved from my team, I’ll merge your changes cut a new release. 

Thank you for your contributions!
-Brian

**Comment by pepesenaris** [comment]
Thanks and have a great day
