### ISSUE TITLE
Set TAG on runtime

### ISSUE THREAD

**Issue by vinyoliver** [CircleCI-Public/aws-ecr-orb#25]
### Orb version
3.1.0

### What happened
I'm not being able to set the TAG parameter on runtime. On my workflow, I got a job that downloads the project and creates a release. I'd like to take the release number and pass to build_and_push_image as an environment variable. I've tried the following 

```
-release_job
  export TAG_VERSION=`git describe --abbrev=0 --tags`

```
then on the ecr job

```
- aws-ecr/build_and_push_image:
          tag: TAG_VERSION
```

Also tried to set the environment variable using 
`echo 'export TAG_VERSION=`git describe --abbrev=0 --tags`' >> $BASH_ENV`

Also tried `tag: ${TAG_VERSION}`

**Comment by lokst** [comment]
@vinyoliver I would recommend using `pre-steps` to set the value of `TAG_VERSION`. (See: https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps)
