### ISSUE TITLE
Build only, then Push only example

### ISSUE THREAD

**Issue by odie5533** [CircleCI-Public/aws-ecr-orb#252]
## What would you like

I would like to be able to run my pytest suite at the same time that the Docker image is building. Then after both are done, a Hold for Approval step, and then push.

## What you would like added

I see PR #237 by @brivu adds back the push-image command. I would like to request an example config.yml, or whether it is possible using the new commands, to run both a test Job and the aws-ecr/build-image at the same time, followed by a push-image step? Are ecr-login or tag-image needed?

## Why is this needed

I currently use just aws-ecr/build-and-push-image which does it all, but I believe separating the commands would be faster since it would allow a test Job to run while the Docker image is building. This could save minutes on my CircleCI workflow.

**Comment by martyzz1** [comment]
https://circleci.com/developer/orbs/orb/martyzz1/aws-ecr-extra

I developed this to deal with this issue. I wanted to build images, then run tests against the built image, before pushing...
