### ISSUE TITLE
8.2.x breaks aws-ecr/build-and-push-image with path

### ISSUE THREAD

**Issue by bjornharrtell** [CircleCI-Public/aws-ecr-orb#256]
It seems it doesn't change build context path.

**Comment by kevin-lot** [comment]
I have the same issue.
The documentation has an error.

In job `build-and-push-image`:
```
path | Path to the directory containing your Dockerfile and build context. Defaults to . (working directory). | No | . | string
```
But `path` doesn't override `build-path` of `build-image` command wich has "." by default.

**Comment by kevin-lot** [comment]
@bjornharrtell A temporary fix is to define "dockerfile" parameter with a full path that points your dockerfile and to define "path" parameter for context.
