### ISSUE TITLE
ECR push failing with EOF error

### ISSUE THREAD

**Issue by devops-omneky** [CircleCI-Public/aws-ecr-orb#259]
### Orb version

  8.2.1

### What happened

  Docker push failing at 50% with EOF error. 
  REF: https://app.circleci.com/pipelines/github/omneky-org/dashboard-python/720/workflows/7fdaebb5-1f84-42f4-934c-92931b2ce3f1/jobs/718

### Expected behavior

The push should be successful

**Comment by brivu** [comment]
Hey @devops-omneky, 

Can you please send me the snippet of config you are trying to run? Is it just the `push` command or is it the `build-and-push-image` job?

Let me know and I'll check it out! 

Best, 
Brian

**Comment by maxb94** [comment]
@devops-omneky the issue for me was missing the permission "ecr:InitiateLayerUpload" for my IAM user. Look at CloudTrail > Event History in the AWS dashboard for a detailed error message.

**Comment by brivu** [comment]
Thanks @maxb94! I've tested this out as well and the `ecr:InitiateLayerUpload` permissions is required for the command to work. 

@devops-omneky, can you check your `IAM` permissions and let me know if that's what's missing? I am going to close this issue but feel free to open if you still have problems.
