### ISSUE TITLE
aws-ecr-orb Not Compatible with AWS CLI version < 1.17.10

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/aws-ecr-orb#264]
### Orb version

`aws-ecr: circleci/aws-ecr@8.2.1`

### What happened

We ran the orb on a self-hosted runner with the AWS CLI version aws-cli/1.16.312 installed. The following error was presented:

```
#Shellcheck disable=SC2002
if [ -f "$HOME/.docker/config.json" ] && cat ~/.docker/config.json | grep "${ORB_VAL_ACCOUNT_URL}" > /dev/null 2>&1 ; then
    echo "Credential helper is already installed"
else
    aws "${ECR_COMMAND}" get-login-password --region "${ORB_EVAL_REGION}" "$@" | docker login --username AWS --password-stdin "${ORB_VAL_ACCOUNT_URL}"
fi

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument operation: Invalid choice, valid choices are:
```

### Expected behavior

I don't actually know what the desired behavior should be, it could be any of the following:

1. Utilize the command `aws ecr get-login` for earlier versions of the AWS CLI (versions prior to 1.17.10 it is believed) - I think this might be 
2. Exit if the AWS CLI version is older than 1.17.10.
3. Or the documentation could reflect that a version of the AWS CLI greater than 1.17.10 should be used - I think this might be an ideal solution but I could not find where to enter this into the documentation.
4. Something else?

**Comment by brivu** [comment]
Hey @colinbjohnson, 

Thanks for opening this issue. I went ahead and updated the command and job descriptions to include incompatibility issues with version 1 in PR #278. 

Thanks again for your input!

Best, 
Brian
