### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by psoares-resilient** [CircleCI-Public/aws-ecr-orb#27]
### Orb version
Applies to <=4.0.0

### What happened
When new versions are published, It would be nice to see what has been changed from one version to another. Particularly when it is a breaking change (change in major).

### Expected behavior
CHANGELOG.md exists and is up to date, possibly following this: https://keepachangelog.com/en/1.0.0/ as part of your release process, make sure that the file is updated.

**Comment by iynere** [comment]
great idea, thank you @psoares-resilient we should implement this across the board for all our first-party orbs tbh

**Comment by gmemstr** [comment]
I second this, going to take a look at what it would take to implement this for orbs across the board. As it stands now, it's definetly "best guess" when it comes to what's changed between versions, especially within the orb registry itself.

**Comment by gmemstr** [comment]
This is a larger conversation internally and we hope to have more details to share soon!

**Comment by sibelius** [comment]
any progress on orb changelog?

**Comment by mtwilliams5** [comment]
Any progress on orb changelogs? There's been a fair number of changes to config files needed over the last two major versions here, which you can only figure out by digging through the changed files or trial-and-error on builds.
