### ISSUE TITLE
403 Forbidden pushing image

### ISSUE THREAD

**Issue by mdavidovichHst** [CircleCI-Public/aws-ecr-orb#273]
I am having the same issue from the issue linked belfow however downgrading to 7.x.x did not help me.  Plus I couldn't find the doc for the config and it's quite different. 

The orb step to login to ECR is successful so I'm not understanding what's forbidden. 

Any thoughts on this?  Could it be I'm lacking a permission in my policy for ECR?

Downgrading to `7.0.0` pushes images to ECR successfully. Same doesn't work with `8.1.2`. Thanks @sidewaiise for mentioning the version number.

_Originally posted by @siddharthsathe in https://github.com/CircleCI-Public/aws-ecr-orb/issues/200#issuecomment-1153776869_

**Comment by brivu** [comment]
Hey @mdavidovichHst, 

Thanks for letting me know. I took a look at issue #200 and it looked like something was up with the `skip-when-tags-exist` parameter. 

I'm trying to reproduce this to start working on a fix. Can you send me a snippet of your config and let me know how you've set things up on the `aws` side of things so I can run some test? 

Let me know and we'll try to get a fix into the next release. 

Thanks, 
Brian

**Comment by brivu** [comment]
Hey @mdavidovichHst, 

I'm going to close out this issue for now but feel free to re-open if you're still having this problem. 

Thanks!
Brian

**Comment by mdavidovichHst** [comment]
@brivu, no problem!

Thanks for following up and I'll try to revisit this when I can.

MD
