### ISSUE TITLE
Whitelist AWS account for image pull

### ISSUE THREAD

**Issue by virtualdom** [CircleCI-Public/aws-ecr-orb#28]
### Orb version

Applies to >=4.0.2

### What happened

Would be neat to have parameters for AWS account IDs to give secondary access to created repos. If a config has `create-repo: true`, there could be another property `secondary-account-ids` that takes a list of AWS account IDs to add to a policy that allows for image pulling from those accounts.

### Expected behavior

By using the orb and listing `create-repo: true` and `secondary-account-ids`, my build should build and push an image to a newly-created repo, and my secondary accounts should be able to pull from the newly-created repo.

**Comment by brivu** [comment]
I'm closing this request for now but if this is still of interest, please reopen and our team will take a look.  Thank you!
