### ISSUE TITLE
add assume role capabilities to build image command

### ISSUE THREAD

**Issue by Almenon** [CircleCI-Public/aws-ecr-orb#291]
## What would you like to be added

Add assume role capabilities to build image command

## Why is this needed

To be able to assume a role to pull ECR image for speeding up the build.
Also by adding params for assume role the build-image interface would more closely match the build-and-push-image interface.

## Workaround

Logging into ECR in a separate step

**Comment by brivu** [comment]
Hey @Almenon, can you give me more details into what you're looking for? If you use the `aws-cli/setup` command from the AWS CLI Orb before running any `aws-ecr` commands and jobs, you should be able to create different profiles and then use them directly in the ECR jobs itself.

**Comment by brivu** [comment]
Hey @Almenon, 

You can actually do this now in the `build_and_push_image` job with PR #292. You will need to set the `container_registry_login` parameter to `true` and then provide a custom login step to whichever container registry you'd like to log into. 

I should be cutting a new release for this feature within the next week or so. 

Best, 
Brian
