### ISSUE TITLE
Release 9.0

### ISSUE THREAD

**Issue by dhilmathy** [CircleCI-Public/aws-ecr-orb#294]
## What would you like to be added
- Release `9.0`. I can see the code change in `master` and the examples point to that. But, it is not released.

## Why is this needed
- Better align with other similar _AWS_ (aws-s3), where we can use `auth` for `setup`.

**Comment by brivu** [comment]
Hey @dhilmathy, 

I'm making some minor tweaks to the orb and will release it in the next couple of hours. 

Thanks! 
Brian
