### ISSUE TITLE
Documentation and README inconsistencies

### ISSUE THREAD

**Issue by hwaxxer** [CircleCI-Public/aws-ecr-orb#30]
### Orb version
4.0.1

### What happened
Expected `repo` to be a URI as per the documentation. Instead, it's the repo name.

I left `account-url` blank, but the interpolated URI becomes `<< parameters.account-url >>/<< parameters.repo >>:<< `

### Expected behavior
Since `repo` is the only required parameter, I would expect it to be a URI and not a repository name.

**Comment by KyleTryon** [comment]
Hello @hwaxxer,

Can you point to which documentation you are referring to?

In the orb documentation for the `build-and-push-image` command the `repo` parameter description reads `Name of an Amazon ECR repository`.

This is not the only "required" parameter in the sense that it is all that needs to be supplied. Many of the other parameters simply have pre-defined values but are still required.

A potentially appropriate change I could see here is updating the name of the parameter from `repo` to `repo-name` if that would reduce ambiguity.

**Comment by ghostsquad** [comment]
I also noticed that some of the parameters have a default value, but are still "required" which completely negates the default value.

**Comment by gmemstr** [comment]
As per https://github.com/CircleCI-Public/aws-ecr-orb/pull/31, this was fixed in `4.0.3`, and is accurate in the documentation now. If you find this is not the case, feel free to reopen!
