### ISSUE TITLE
Error Thrown: existing instance for "DLC_builder" but no append mode

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/aws-ecr-orb#308]
### Orb version

`aws-ecr: circleci/aws-ecr@9.0`

### What happened

We performed a `build_and_push_image` job after updating to orb version 9.0. We utilize a [CircleCI self-hosted runner](https://circleci.com/docs/runner-overview/) based on the `ubuntu:latest` Docker Image.

We got the following error:

```
ERROR: existing instance for "DLC_builder" but no append mode, specify --node to make changes for existing instances

Exited with code exit status 1
```

### Expected behavior

We expected the job to run.

### Other Notes

Still collecting information regarding this failure but it does seem (sort-of) like the `DLC_builder` builder exists but is not being found and an attempt is being made to recreate the given builder.

**Comment by trevorr** [comment]
This is a regression introduced in #304. I had to downgrade to 9.0.0 as a workaround.

**Comment by colinbjohnson** [comment]
I did the same (meaning using version 9.0.0).

**Comment by dswansonvizio** [comment]
I'm still having the same issue @brivu on 9.0.4
`
+ docker buildx create --name DLC_builder --use
ERROR: existing instance for "DLC_builder" but no append mode, specify --node to make changes for existing instances
`

**Comment by MNeverOff** [comment]
I cam confirm that this issue is intermittently present on `aws-ecr: circleci/aws-ecr@9.1.0` as well. Downgrading to 9.0.0 seemed to have helped. 

For me it doesn't occur every time but for every time it does it's within the job where I have two consecutive `aws-ecr/build_and_push_image` calls (different rrepos/egions).
