### ISSUE TITLE
AWS ECR Credential Helper

### ISSUE THREAD

**Issue by nnovaeshc** [CircleCI-Public/aws-ecr-orb#317]
## What would you like to be added

I'd like to know if there's a particular reason why this orb doesn't use a credential helper instead of passing the password via `password-stdin`

## Why is this needed

As per [Docker documenation](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) it should be a safer option to use a credential helper. I can contribute with a PR, but wanted to understand if there are any cases where this would be a bad idea

**Comment by brivu** [comment]
Hey @nnovaeshc - Thanks for opening this issue.  I like the idea but have not had the bandwidth to implement credential helper yet. It would be super helpful if you opened a PR. I'll make sure it gets tested and merged.
