### ISSUE TITLE
Only the first --build-arg is passed to Docker build in v9.0.2

### ISSUE THREAD

**Issue by hubby-work** [CircleCI-Public/aws-ecr-orb#324]
### Orb version

9.0.2

### What happened

Passing multi line values to extra_build_args in the build_and_push_image job results in only the first --build-arg being added to the docker build command.

For example - 

```
extra_build_args: |
            --build-arg ARG1=<< parameters.arg1 >>
            --build-arg ARG2=<< parameters.arg2 >>
            --build-arg ARG3=<< parameters.arg3 >>
```
Results in only --build-arg ARG1=arg1value being passed to the underlying docker build command

### Expected behavior

All build args should be passed to the docker build command.

This has been the behaviour in v9.0.0 and v9.0.1

**Comment by brivu** [comment]
Hey @mattbasta,

Thanks for writing in and letting us know. I've tested this out on my end and if you replace the | with >- like below, it should work for you:

extra_build_args: >-
  --build-arg ARG1=<< parameters.param_1 >>
  --build-arg ARG2=<< parameters.param_2 >>
  --build-arg ARG3=<< parameters.param_3 >>
In doing, my docker command had all three build args:

+ docker buildx build -f workspace/sample/Dockerfile -t ************.dkr.ecr.*********.amazonaws.com/aws-ecr-orb-ab26c21-build-test-then-push-with-buildx:alpha --platform linux/amd64 --progress plain --build-arg ARG1=test_1 --build-arg ARG2=test_2 --build-arg ARG3=test_3 --load .

I'll go ahead and update the parameter descriptions to inform users. Thanks again!

**Comment by afterdigital** [comment]
Thanks @brivu, very much appreciated!
