### ISSUE TITLE
Expressions no longer evaluated? 

### ISSUE THREAD

**Issue by dan-lind** [CircleCI-Public/aws-ecr-orb#328]
### Orb version
9.0.2

### What happened
We migrated from v8 to v9, we use expressions like this, in this example to lowercase all repo names
`repo: $(tr [A-Z] [a-z] \<<< "$CIRCLE_PROJECT_REPONAME")`

### Expected behavior
We expected this to still work in v9, but it looks like something changed and the expressions is no longer evaluated

**Comment by brivu** [comment]
Hey @dan-lind - thanks for opening this issue. We've solved this in PR #321. We're going to make a new major release soon that will include this fix.
