### ISSUE TITLE
Cannot login to multiple ECRs with version 9.0.3

### ISSUE THREAD

**Issue by ahamilton55** [CircleCI-Public/aws-ecr-orb#333]
### Orb version

9.0.3

### What happened

We login to two ECRs in our CI job. It was working fine with 9.0.2 but with the move to using the ecr-login and the setup it now fails on the second login.

We get the following error on the second login:
```
jq: error: Could not open file .credHelpers[$url] = $helper: No such file or directory
```

### Expected behavior

The expected behavior is that the  `~/.docker/config.json` should be updated to allow for logins to multiple ECRs.

**Comment by evilensky** [comment]
Same for. Hope your proposed merge is fixed quickly!
