### ISSUE TITLE
Bugfix: PATH parameter does not override BUILD_PATH parameter as docs suggest

### ISSUE THREAD

**Issue by DevBaca** [CircleCI-Public/aws-ecr-orb#342]
### Orb version

9.1.0

### What happened

The parameter [description](https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/jobs/build_and_push_image.yml#L119-L122) for `path` on the `build_and_push_image` job is incorrect. 

`PATH` does not ever seem to override `BUILD_PATH` and specifying a non-default PATH parameter leaves the `BUILD_PATH` as the default.

Example of build path from the script: https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/scripts/docker_buildx.sh#L97

Note that in none of the jobs/commands leading up to the call of the `build_image` script never overwrites `BUILD_PATH`

### Expected behavior

Either we update the description or update the code in a way that handles `PATH` overriding the default `BUILD_PATH` when specified.  If we go the latter, then also make sure we allow for both `PATH` and `BUILD_PATH` to be specified without `BUILD_PATH` being overwritten.

**Comment by marboledacci** [comment]
The description is updated in version https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=9.3.2
