### ISSUE TITLE
build to local and for one platform only and do not push image

### ISSUE THREAD

**Issue by bob-rohan** [CircleCI-Public/aws-ecr-orb#346]
### Orb version

9.1.0

### What happened

Unable to 
- build to local &
- for one platform only &
- do not push image

```
  elif [ "${ORB_BOOL_PUSH_IMAGE}" -eq "0" ] && [ "${number_of_platforms}" -le 1 ];then
    set -- "$@" --load
  fi
```

### Expected behavior

Able to 
- build to local &
- for one platform only &
- do not push image

Per Docker examples, see scratch. https://docs.docker.com/build/building/multi-stage/

**Comment by marboledacci** [comment]
I don't understand what your issue is, could you explain better?

**Comment by bob-rohan** [comment]
I would like to build to local, for a single platform, without pushing. This is used to build an artifact which is extracted from the image, and subsequently uploaded to somewhere else. The above code block prohibits this behaviour.

**Comment by marboledacci** [comment]
I still don't understand, so you don't want the --load parameter added?

**Comment by bob-rohan** [comment]
correct `--load` is shorthand for `--output=type=docker` , which causes a conflict when attempting to output to local

**Comment by marboledacci** [comment]
Is there a reason why you need to use this orb for that? This doesn't seem to be related to ECR, and the docker-orb already lets you do it.

**Comment by bob-rohan** [comment]
yeah this is fine, thanks
