### ISSUE TITLE
Error when providing multiple comma-separated platforms

### ISSUE THREAD

**Issue by marc7806** [CircleCI-Public/aws-ecr-orb#351]
### Orb version
9.3.1

### What happened

Plugin throws error when calling `docker pull` in the `aws-ecr/build_and_push_image` step when providing comma-separated list of platforms (e.g. `platform: linux/amd64,linux/arm64`)
The error message we receive is:
```
Error response from daemon: "amd64,linux" is an invalid component of "linux/amd64,linux/arm64": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```

After some analysis, we found out that this issue gets introduce by [this](https://github.com/CircleCI-Public/aws-ecr-orb/compare/v9.3.0...v9.3.1) change. Docker pull does not support a comma-separated list of platforms, but docker buildx does support it. Also see #344 

### Expected behavior

We should not get any error when providing a comma-separated list of platforms

**Comment by marboledacci** [comment]
This should be solved in this new version https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=9.3.2

**Comment by marc7806** [comment]
Issue is resolved and can be closed. Thank you!
