### ISSUE TITLE
build_extra_arg quoting issue

### ISSUE THREAD

**Issue by Copper-Roc** [CircleCI-Public/aws-ecr-orb#361]
### Orb version
v9.3.4

### What happened
When using a build arg that has spaces in it, the code ends up adding extra quotes

When using this parameter
```extra_build_args: --build-arg TEST="This is a test"```
I am seeing this output
```docker buildx build -f ./Dockerfile -t AWS_ACCOUNT_ID.dkr.ecr.*********.amazonaws.com/mycontainer:dev-8734-367d0a3 --platform linux/amd64 --progress plain --build-arg '"TEST=This' is a 'test"' --push .```

### Expected behavior

```docker buildx build -f ./Dockerfile -t AWS_ACCOUNT_ID.dkr.ecr.*********.amazonaws.com/mycontainer:dev-8734-367d0a3 --platform linux/amd64 --progress plain --build-arg TEST="This is a test" --push .```

I am pretty sure this issue is caused by https://github.com/CircleCI-Public/aws-ecr-orb/pull/310

**Comment by marboledacci** [comment]
This should be solved in version 9.3.5. When passing args with spaces use this syntax: `--build-arg=TEST='This is a test'`. The = in build-arg is important to understand everything as one argument, and the single quotes on the value are important to avoid splitting the text.
For single word arguments you can keep using the syntax you are using.
