### ISSUE TITLE
can't pass the check by command "circleci config process .circleci/config.yml"

### ISSUE THREAD

**Issue by ozbillwang** [CircleCI-Public/aws-ecr-orb#41]
### Orb version

got different issues with different orb versions

### What happened

With sample (https://circleci.com/blog/orbs-aws-ecr/) by using `0.0.4`, this pipeline work with command `circleci config process .circleci/config.yml`

I'd like to manage the region, account-url, repo and tag name with CONTEXT variables or CIRCLE variables.

```
workflows:
  build_test_deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          region: ${AWS_DEFAULT_REGION}
          account-url: ${AWS_ACCOUNT_ID}.dkr-ecr.${AWS_DEFAULT_REGION}.amazonaws.com
          repo: ${REPO_NAME}
          tag: 1.0.${CIRCLE_BUILD_NUM}
```

between version >0.0.4 and < 5.0.0, I got below error
```
$ circleci config process .circleci/config.yml

Error: Error calling workflow: 'build_test_deploy'
Error calling job: 'aws-ecr/build_and_push_image'
Type error for argument region: expected type: env_var_name, actual value: "${AWS_DEFAULT_REGION}" (type string)
Type error for argument account-url: expected type: env_var_name, actual value: "${AWS_ACCOUNT_ID}.dkr-ecr.${AWS_DEFAULT_REGION}.amazonaws.com" (type string)
```
for version >5.0.0 to latest version 6.1.0, I got below error
```
$ circleci config process .circleci/config.yml
Error: Error calling workflow: 'build_test_deploy'
Cannot find a definition for job named aws-ecr/build_and_push_image
```

### Expected behavior

should work as `0.0.4`

**Comment by iynere** [comment]
that's because we renamed the job to `build-and-push-image` in the laster versions @ozbillwang 

https://circleci.com/orbs/registry/orb/circleci/aws-ecr

please give it a shot with that name & let us know how it goes

**Comment by ozbillwang** [comment]
I went through the name three times,  then know the differences (change _ to -) 

Thanks to point this.
