### ISSUE TITLE
I am surprise this repo doesn't manage release/tag properly 

### ISSUE THREAD

**Issue by ozbillwang** [CircleCI-Public/aws-ecr-orb#42]
The whole repo has only one release `v6.1.0-minor ` currently

How to manage the older versions? How to trace the changes between different versions?

**Comment by iynere** [comment]
please see https://circleci.com/orbs/registry/orb/circleci/aws-ecr @ozbillwang

**Comment by iynere** [comment]
we're working on better automated changelogs & release tagging on the github side of things, but currently, it's not standardized across our 1st-party orb repos, so your best bet is using the orb registry & the circleci cli:

https://circleci-public.github.io/circleci-cli/circleci_orb_source.html

**Comment by ozbillwang** [comment]
Sure, @iynere 

Could you show me something that I can find out the differences between version 6.1.0 and 6.0.0 or 5.0.0?

**Comment by iynere** [comment]
use `circleci orb source circleci/aws-ecr@6.1.0` & compare the output to the output of whatever other version you want to compare

or use the 'releases' dropdown on the registry page : https://circleci.com/orbs/registry/orb/circleci/aws-ecr
