### ISSUE TITLE
There is a typo in the official documentation - `account-url`

### ISSUE THREAD

**Issue by arsiaardalancanopy** [CircleCI-Public/aws-ecr-orb#43]
### Orb version
6.1.0

### What happened
description for `account-url` has a typo:
It is:
`{awsAccountNum}.dkr-ecr.us-west-2.amazonaws.com`

### Expected behavior
It should be:
`{awsAccountNum}.dkr.ecr.us-west-2.amazonaws.com`

**Comment by iynere** [comment]
@arsiaardalancanopy thank you! can you submit a PR ?

should be changed in any file within https://github.com/CircleCI-Public/aws-ecr-orb/tree/master/src where the `account-url` parameter appears

**Comment by gagandeepp** [comment]
I will take this one
