### ISSUE TITLE
Docker run failure

### ISSUE THREAD

**Issue by alaxalves** [CircleCI-Public/aws-ecr-orb#59]
### Orb version

version: 2.1

### What happened

It seems that there is a missing package.json file.

![image](https://user-images.githubusercontent.com/19597045/66074800-71af1000-e530-11e9-9ef9-d78c3ae7f7e2.png)

### Expected behavior

app should start!

**Comment by lokst** [comment]
@alaxalves Would you mind elaborating on how this relates to usage of the aws-ecr orb? It would be great if there is a CircleCI job you could link us to!

**Comment by alaxalves** [comment]
> @alaxalves Would you mind elaborating on how this relates to usage of the aws-ecr orb? It would be great if there is a CircleCI job you could link us to!

This happens when I build and run this repository's Dockerfile and resulting container, respectively.

**Comment by gmemstr** [comment]
The Docker image included in the repository is only intended to be used in the integration testing, and does nothing on it's own. That said, I think it could do with some tweaks to make it more generic, since we don't care much about the image.
