### ISSUE TITLE
Now way to pass env/args to the docker file?

### ISSUE THREAD

**Issue by akash-rajput** [CircleCI-Public/aws-ecr-orb#74]
## What would you like to be added
There should be a way to pass args for the build being generated. Currenty cannot find such documentation for the same. If there's a way please point out.

## Why is this needed

We need to pass the sensitive data from env to args for the docker builds.

**Comment by n-batalha** [comment]
Not a maintainer, but while initially thought I had this, it this seems a duplicate of https://github.com/CircleCI-Public/aws-ecr-orb/issues/5 resolved by https://github.com/CircleCI-Public/aws-ecr-orb/pull/8.

You need to use this new param `extra-build-args` to set `--build-arg ...` and set `ARG` variables in your Dockerfile.

**Comment by lokst** [comment]
Apologies for the delay in response @akash-rajput. @n-batalha 's suggestion sounds like a good one to me. Let us know if it helps!
