### ISSUE TITLE
Allow folks to disable AWS CLI installation and choose AWS CLI version

### ISSUE THREAD

**Issue by chrisgilmerproj** [CircleCI-Public/aws-ecr-orb#86]
## What would you like to be added

I am already running a docker image with AWS CLI v2 installed. Using this orb causes AWS CLI v1 to be installed. While the AWS CLI v2 does change the login procedure I feel like a switch statement could fix that.

I envision this change:

```text
 - aws-ecr/build-and-push-image:
          ...
          install-aws-cli: false
          aws-cli-version: v2
          ...
```

The default for `install-aws-cli` could be set to `true` which maintains backward compatibility. The default for `aws-cli-version` could be set to `v1` which would also maintain backward compatibility. 

## Why is this needed

The re-installation feels redundant and also adds time (and thus uses credits) that isn't necessary. I have a project requirement to use AWS CLI v2 and to have it baked into my main image to use a specific version. That means it's not as simple as choosing to use a different base image so I can also use this orb. 

This kind of increased flexibility would help folks out as they transition from AWS CLI v1 to v2 and also help reduce costs for folks on CircleCI.

**Comment by lokst** [comment]
@chrisgilmerproj Thanks for the feedback! We'll be looking into how we can better support aws cli v2 users.

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj Thanks for the feedback! We'll be looking into how we can better support aws cli v2 users.

Thanks! I appreciate any work you do on this. Also, your module is otherwise flawless and has really helped my project out so we're grateful for your efforts.

**Comment by gmemstr** [comment]
@chrisgilmerproj The v2 of the AWS CLI should now be installed by default, curious if you believe it's worth keeping this open for the feature of picking the version or disabling installation.

**Comment by chrisgilmerproj** [comment]
> @chrisgilmerproj The v2 of the AWS CLI should now be installed by default, curious if you believe it's worth keeping this open for the feature of picking the version or disabling installation.

This is great news! I would absolutely like to control the version as we have run into issues in the past having the CLI our devs use being out of sync from what CircleCI has. So any work on that would be helpful.

**Comment by andreialecu** [comment]
@gmemstr I have an use case for disabling installation. I opened https://github.com/CircleCI-Public/aws-ecr-orb/issues/135 before finding this.

**Comment by brivu** [comment]
Hey @chrisgilmerproj 

I'm Brian from CircleCI's CPE Team.  I just wanted to let you know thatI've taken care of this issue and it'll be merged with the next PR.

Thanks for your contribution! 
Brian

**Comment by chrisgilmerproj** [comment]
Brian, Thanks for the update. I appreciate that you folks kept working on this.
