### ISSUE TITLE
aws-cli installation fails when .python-version is set in repo

### ISSUE THREAD

**Issue by Nyefan** [CircleCI-Public/aws-ecr-orb#88]
### Orb version

6.7.0

### What happened

The ecr/build-and-push-image is called with minimal parameters (repo, create-repo, tag, and region).  A `.python-version` file specifies the python version to use during the execution of the Dockerfile commands (which is included in the base image).  The `Install AWS CLI` step fails with the following message:

```bash
#!/bin/bash -eo pipefail
export PIP=$(which pip pip3 | head -1)
if [[ -n $PIP ]]; then
  if which sudo > /dev/null; then
    sudo $PIP install awscli --upgrade
  else
    # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
    $PIP install awscli --upgrade --user
  fi
elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
  cd
  curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  unzip awscli-bundle.zip
  if which sudo > /dev/null; then
    sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  else
    # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
    awscli-bundle/install -b ~/bin/aws
  fi
  rm -rf awscli-bundle*
  cd -
else
  echo "Unable to install AWS CLI. Please install pip."
  exit 1
fi
```

```bash
pyenv: version `2.7.17' is not installed (set by /home/circleci/project/.python-version)

Exited with code exit status 1
```

### Expected behavior

The .python-version in the local repo should be masked or ignored by the aws-cli installation step since that is completely independent of build step which requires it.  I am able to successfully build the image by removing the .python-version from the repo and creating it in the Dockerfile, but this is not ideal.

**Comment by lokst** [comment]
@Nyefan It seems to be the behaviour of `pip` to use pyenv which would pick up on the `.python-version`. Could you configure the job with [`pre-steps`](https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps) to remove the `.python-version` file as a workaround?

**Comment by Nyefan** [comment]
This works, but it still seems kludgey to me - is there a reason aws-cli has to be installed *after* the repo is checked out?

**Comment by lokst** [comment]
@Nyefan I don't think it has to be, and changing the installation order sounds like a good solution to this, thank you. I'll post updates here after trying that out.

**Comment by gmemstr** [comment]
Installing the CLI before checking out the repository would resolve this issue - it's very common to have the checkout step execute first in the job, but it doesn't have to be. I'm going to go ahead and close this issue, since it isn't directly related to the orb, but feel free to reopen if you feel we should dig in a bit deeper :)
