### ISSUE TITLE
Building with multiple tags broken

### ISSUE THREAD

**Issue by andheiberg-gelato** [CircleCI-Public/aws-ecr-orb#89]
### Orb version

6.2.0

### What happened

```
- aws-ecr/build-and-push-image:
    repo: your-repo-name
    tag: tagone,tagtwo
```

Results in:

```
docker build \
  -f Dockerfile \
  -t your-repo-name:tagone,tagtwo \
  .
invalid argument your-repo-name:tagone,tagtwo" for t: invalid reference format
See 'docker build --help'.

Exited with code exit status 125
```

### Expected behavior

Docker build should succeed and the command produced should be:

```
docker build \
  -f Dockerfile \
  -t your-repo-name:tagone \
  -t your-repo-name:tagtwo \
  .
```

### Context

I guess it's the escaping done here https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-image.yml#L47

When I try locally it works just fine:

```
#!/bin/bash

docker_tag_args=""
IFS="," read -ra DOCKER_TAGS <<< "tagone,tagtwo"
for tag in "${DOCKER_TAGS[@]}"; do
  docker_tag_args="$docker_tag_args -t image:$tag"
done

echo $docker_tag_args // -t image:tagone -t image:tagtwo
```

So the bash is valid and works. My conclussion would be that `\<<<` is the problem. But I don't know what this is run through before it's run? It appears it's trying to get around parameter replacement for `<< ... >>`.

**Comment by lokst** [comment]
@andheiberg-gelato We have a test case for building with multiple tags, which looks to be passing: https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/.circleci/config.yml#L64

Could you try upgrading to version `6.8.0` and let us know if you still encounter the issue?

**Comment by andheiberg-gelato** [comment]
@lokst this does appear to work. Thank you 👍
