### ISSUE TITLE
Support AWS_DEFAULT_REGION environment variable by default

### ISSUE THREAD

**Issue by taurelius** [CircleCI-Public/aws-ecr-orb#91]
## What would you like to be added

Change the default region environment variable value to  `DEFAULT_AWS_REGION` from `AWS_REGION` 

## Why is this needed

The orbs current default doesn't match up with the AWS CLI or the AWS CLI orb, meaning when using them both together, one of the default parameters has to be overridden (or they both need to be set).

It looks like this change was made a while back for the CLI orb https://github.com/CircleCI-Public/aws-cli-orb/issues/2

**Comment by taurelius** [comment]
Just doing further reading and it looks like `AWS_REGION` is back in [AWS CLI v2](https://github.com/aws/aws-cli/pull/4934) so understand if this is left for now if v2 support is in the works - though I would argue while the orb is based on v1 it should use `AWS_DEFAULT_REGION`.

Whatever the case though it would be nice to have the CLI and ECR orbs aligned.

**Comment by gmemstr** [comment]
The orb has been updated to use v2 of the AWS CLI by default, so going ahead and marking this as closed :) Feel free to reopen if you feel this is something we should look into further.
