### ISSUE TITLE
Wrong login docker with multiple workflows and account urls:

### ISSUE THREAD

**Issue by sebdec** [CircleCI-Public/aws-ecr-orb#93]
### Orb version

6.7.1

### What happened

command: build-and-push-image

**1) workflow A**
parameters : account-url: A_AWS_ACCOUNT_URL
RUN  : OK

**2) workflow B**
parameters : account-url: B_AWS_ACCOUNT_URL
RUN:
- Log into Amazon ECR : retrieve login docker from the **workflow A** (in cache maybe)
- it doesn't login with the specified account url (B_AWS_ACCOUNT_URL)
- docker push: **FAIL** : no basic auth credentials

Seems to be an issue with multiple workflows and different account urls
docker login stays maybe in the executor cache: because at the beginning of workflow B: the /home/circleci/.docker/config.json contains the docker login of workflow A.

### Expected behavior

- command build-and-push-image take into account the defined account-url to login to docker

**Comment by sebdec** [comment]
after more investigation: this issue is probably related with https://github.com/CircleCI-Public/aws-ecr-orb/pull/85/files.
Then, if the profiles can resolve that, I don't understand the utility of the ecr-login-for-secondary-account command.

**Comment by lokst** [comment]
@sebdec https://github.com/CircleCI-Public/aws-ecr-orb/pull/85 has been merged, would you like to try using `circleci/aws-ecr@6.8.0` ? As for the `ecr-login-for-secondary-account` command, I believe this was implemented some time ago and may need reviewing if it still has utility.

**Comment by sebdec** [comment]
Thank you @lokst,  It works well !
I close the issue
