### ISSUE TITLE
[Feature Request] Parameter to choose if to install aws/cli or not.

### ISSUE THREAD

**Issue by markrity** [CircleCI-Public/aws-ecr-orb#95]
## Parameter to choose if to install aws/cli or not.
```
- aws-ecr/build-and-push-image:
     install_cli: false
```
## Why is this needed

I want to be able to skip this step , since it executed on every build and push, sometimes you have already done a aws-cli/setup or already pushed an image at step before and its just waste of time to instsall it again.
I know that there is a step to check if there is an aws already installed.
But when I use latest orb of aws-cli , it installs AWS CLI v2 and then ECR orb install V1 again...

**Comment by gmemstr** [comment]
While the orb now installs v2 by default, this is something I'm seeing a few issues about. Looking into implementing a boolean flag for installing the CLI.

**Comment by gmemstr** [comment]
Closing to track progress in #86
