### ISSUE TITLE
Document extra-build-args

### ISSUE THREAD

**Issue by silasb** [CircleCI-Public/aws-ecr-orb#97]
## What would you like to be added

Documenting extra-build-args.

## Why is this needed

I had to hunt through Issues/PRs to find out that this exists.

**Comment by lokst** [comment]
@silasb Thank you for your feedback. The `extra-build-args` parameter is also documented in the orb registry: https://circleci.com/orbs/registry/orb/circleci/aws-ecr

**Comment by gmemstr** [comment]
Given this is document due to the nature of the orb registry listing, I'm going to close this issue. Feel free to open a PR if you feel the documentation could be done better :)
