### ISSUE TITLE
Log into Amazon ECR step uses removed AWS subcommand

### ISSUE THREAD

**Issue by davidmusgrove** [CircleCI-Public/aws-ecr-orb#98]
### Orb version

6.8.2

### What happened

A CircleCI workflow using this orb has started failing in the last day or so, seemingly because the "get-login" subcommand on "aws ecr" has moved from deprecated to absent. Although this gives an exit code of 0 so the step shows as passed, it causes the subsequent push step to fail.

### Expected behavior

It should work as published, the login should work and the push should succeed.

**Comment by PauloCabral-internations** [comment]
HI! 

It's not possible to use docker login with --no-include-email parameter anymore? 
Can you explain the reason why you change this? 

Thank you
